apiVersion: batch/v1
kind: Job
metadata:
  name: wrk2-metrics-merger
  labels:
    jobgroup: wrk2-metrics-merger
  namespace: {{.Release.Namespace}}
spec:
  template:
    metadata:
      name: wrk2-metrics-merger
      labels:
        jobgroup: wrk2-metrics-merger
        app: wrk2-metrics-merger
        custom-affinity: load-generator-node
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 10001
      containers:
      - name: metrics-merger
        image: sagar23192/svcmesh-bench-result-merger-consul:latest
        imagePullPolicy: Always
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus-operated.monitoring:9090"
        args:
        - "http://prometheus-operated.monitoring:9090"
        - "http://pushgateway.monitoring:9091"
