apiVersion: batch/v1
kind: Job
metadata:
  name: wrk2-metrics-merger
  labels:
    jobgroup: wrk2-metrics-merger
  namespace: {{.Release.Namespace}}
spec:
  template:
    metadata:
      name: wrk2-metrics-merger
      labels:
        jobgroup: wrk2-metrics-merger
        app: wrk2-metrics-merger
        custom-affinity: load-generator-node
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 10001
      nodeSelector:
        role: benchmark
      containers:
      - name: metrics-merger
        image: quay.io/kinvolk/svcmesh-bench-results-merger
        imagePullPolicy: Always
        env:
        - name: PROMETHEUS_URL
          value: {{ .Values.prometheusServiceUrl }}
        args:
        - {{ .Values.prometheusServiceUrl }}
        - {{ .Values.pushgatewayURL }}
        - {{ .Values.exportedJobs }}
